// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbwYX2zZxzRJT2tPoafYTL-62RsyzOIMrijIQxVAaAQlxFJ0QyAjUAO5aHbSHJPx_Ngp/exec";
